name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run:  |
          npm install
          npm run format:check
          npm run format:list
          npm run format:write
          npm run fix
          npm run lint
      - name: Build
        run: npm run build-prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
